### ISSUE TITLE
defaultsDeep

### ISSUE THREAD

**Issue by enten** [char0n/ramda-adjunct#118]
```javascript
const defaultsDeep = R.curryN(2, (defaults, options) => R.merge(R.clone(defaults), options))
```

```
(static) defaults(defaultOptions, options) → (non-null) {Object}
```

- R_: `{k: v} → {k: v} → {k: v}`
- RA: `DefaultOptions -> Options -> Defaults`

```js
const DEFAULT = {
  foo: {},
  bar: []
}

RA.defaults(DEFAULT)({}).foo === DEFAULT.foo // true
RA.defaults(DEFAULT)({}).bar === DEFAULT.bar // true

RA.defaultsDeep(DEFAULT)({}).foo === DEFAULT.foo // false
RA.defaultsDeep(DEFAULT)({}).bar === DEFAULT.bar // false
```

**Comment by char0n** [comment]
Hi @enten nice to see ya here ;]

After going through your proposal I realized that the version of `default` in `RA` is implemented wrongly.
The `defaults` function should be alias of `mergeRight` instead of being alias of `merge`. Ramda [cookbook](https://github.com/ramda/ramda/wiki/Cookbook#set-properties-only-if-they-dont-exist) is explicit about it. I'll correct the behavior in next release.

Regarding `defaultsDeep`, ramda already has [mergeDeepRight](http://ramdajs.com/docs/#mergeDeepRight). Isn't that the same behavior as yours `defaultsDeep` ?

**Comment by enten** [comment]
Hi @char0n! You have done a great work!

You're right: it's the same behavior. This issue can be closed.

**Comment by char0n** [comment]
> Hi @char0n! You have done a great work!
Thanks. I'm hoping to see a PR from you when you have more time ;] There is still tons of work to do...

> You're right: it's the same behavior. This issue can be closed.
Cool. And we also corrected the behavior of `defaults`
