### ISSUE TITLE
isNaturalNumber

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1440]
**Is your feature request related to a problem? Please describe.**

Predicate determining if the number is a natural number. Natural numbers according to ISO 80000-2 corresponds to the non-negative integers 0, 1, 2, 3

**Describe the solution you'd like**
```js
isNaturalNumber(1); //=> true
```

**Describe alternatives you've considered**

Excluding zero from the non-negative integers. Though non-negative integers + 0 seems to be more standard set.

**Additional context**

https://en.wikipedia.org/wiki/ISO/IEC_80000

Documentation for [RA.isEven](https://char0n.github.io/ramda-adjunct/2.26.0/RA.html#.isEven) needs to be changed, because it claims that 0 is not a natural number.

**Comment by daksh-goyal** [comment]
@char0n what help do you want on this? How could I contribute?

**Comment by char0n** [comment]
@daksh-goyal you can implement the `isNaturalNumber` function and issue a PR. This is an example how the [PR](https://github.com/char0n/ramda-adjunct/pull/1406/files) could look like.

**Comment by tomokos2** [comment]
@char0n Hi, I am a first time contributor, and I implemented `isNaturalNumber ` according to the PR guidelines. I have also confirmed that all of my test cases pass. All I have left to do is submit the pull request. However, I am having trouble doing so because of errors with prettier and eslint. 

To be specific, when committing the code, I get this error: ` error  Delete `␍`  prettier/prettier`
This error appears across any line of code that includes a semicolon or a newline, so I feel that it is a building problem for me. 
I am running this code on VSCode and Windows10. Do you have any idea what I can do to fix this error so I can commit the code that I have written? Thank you.

**Comment by yadunandanbhat** [comment]
I can change the documentation.

**Comment by char0n** [comment]
@yadunandanbhat go ahead, issue a PR.

**Comment by char0n** [comment]
@tomokos2 sorry for reacting late. If you're having the problem you're describing please `npm run lint:fix`. When running this command, the linter fixes all problems for you. This message comes from [prettier](https://prettier.io/), which guarantees that our code looks consistent regardless of who produced it.

I'm seeing a PR already done by somebody else for `isNaturalNumber`. Would you be able to pick up another issue? We have a lot of issues that are waiting for implementation by [firsttimers](https://github.com/char0n/ramda-adjunct/labels/first-timers-only).

**Comment by tomokos2** [comment]
I see, thanks so much. I will work on a different issue
