### ISSUE TITLE
omitBy

### ISSUE THREAD

**Issue by rockymadden** [char0n/ramda-adjunct#171]
Had use for `omitWhen` yesterday, open to a PR? https://github.com/ramda/ramda/wiki/Cookbook#remove-a-subset-of-keys-from-an-object-whose-associated-values-satisfy-a-given-predicate

Ref: #27

**Comment by char0n** [comment]
Go for it. LGTM

**Comment by char0n** [comment]
Still thinking about it. Can we rename it to `omitBy`? The name just seems more correct and consistent with already existing `pickBy`. Omit when sound a bit  strange.

I would also look at the implementation of [pickBy](http://ramdajs.com/docs/#pickBy) before implementing, so that our predicate function receives `(value, key)` in that order, just to be consistent with `pickBy`.
