### ISSUE TITLE
omitIndexes

### ISSUE THREAD

**Issue by BjornMelgaard** [char0n/ramda-adjunct#174]
looking for better implementation

```ts
import * as R from 'ramda'

interface OmitIndexes {
  <T>(indexes: number[], arr: T[]): T[]
  (indexes: number[]): <T>(arr: T[]) => T[]
}
export const omitIndexes: OmitIndexes = R.curryN(2, function(
  indexes: number[],
  arr: any[]
) {
  const reject = R.addIndex(R.reject)
  const rejectedIndexes = (_: any, i: any) => R.contains(i, indexes)
  const ret = reject(rejectedIndexes, arr)
  return ret
})

```

**Comment by char0n** [comment]
```javascript
const omitIndexes = R.curryN(2, R.compose(R.values, R.omit));
```

**Comment by BjornMelgaard** [comment]
@char0n yeh, I have thought about this, but was concerned about speed

**Comment by char0n** [comment]
@BjornMelgaard I wouldn't worry about that. The point of ramda-adjunct is declarativnes and compos-ability. Or main goal is not performance. IMHO for 90% of use-cases ramda-adjunct is just fine. But if you're building system where performance is the critical factor, I would not recommend to use ramda-adjunct and create use-case based functional with optimized imperative code inside them, so that I get the most performance from JavaScript engine as I possible can.

**Comment by BjornMelgaard** [comment]
@char0n weird, your implementation is not working, I have to make 

```js
const omitIndexes = curryN(2, (x, y) => {
  const m = map(toString, x)
  const o = omit(m, y)
  return values(o)
});
```

whatever, don't want to understand, I'll better use my implementation

**Comment by char0n** [comment]
@BjornMelgaard show me the POC where it's not working pls.

**Comment by BjornMelgaard** [comment]
```
import RA from '../src/index';
import eq from './shared/eq';


describe('omitIndexes', function() {
  it('tests currying', function () {
    const indexes = [1, 3];
    const arr = ['a', 'b', 'c', 'd'];
    const expected = ['a', 'c'];

    eq(RA.omitIndexes(indexes, arr), expected);
    eq(RA.omitIndexes(indexes)(arr), expected);
  });

  it('tests non existing indexes are omitted', function() {
    const indexes = [-1, 1, 3];
    const arr = ['a', 'b', 'c', 'd'];
    const expected = ['a', 'c'];

    eq(RA.omitIndexes(indexes, arr), expected);
  });
});

import { curryN, compose, values, omit } from 'ramda';

/**
 * Returns a partial copy of an array omitting the indexes specified.
 *
 * @func omitIndexes
 * @memberOf RA
 * @since {@link https://char0n.github.io/ramda-adjunct/1.18.1|v1.18.1}
 * @category List
 * @sig [i] -> [a] -> [a]
 * @see {@link http://ramdajs.com/docs/#omit|omit}
 * @param {!Array} indexes The array of indexes to omit from the new array
 * @param {!Array} arr The array to copy from
 * @return {!Array} The new array with indexes not on it
 * @example
 *
 * RA.omitIndexes([-1, 1, 3], ['a', 'b', 'c', 'd']); //=> ['a', 'c']
 */
const omitIndexes = curryN(2, compose(values, omit));

export default omitIndexes;

```

**Comment by char0n** [comment]
No it's not going to work on negative indexes. Just like [pickIndexes](https://char0n.github.io/ramda-adjunct/1.18.0/RA.html#.pickIndexes) doesn't work on negative indexes. 

@BjornMelgaard I would go for consistent behavior for both the functions first. Then we can lift them both so that they support negative indexing (but do we even need it anyway ?).

**Comment by BjornMelgaard** [comment]
No, I dont want this to work with negative indexes, I want it to ignore `-1`

P.S. because its pretty neat to compose omitIndexes with findIndex, when findIndex returns `-1`

**Comment by char0n** [comment]
Yeah I get it now.

**Comment by char0n** [comment]
Job for me: document on ramda cookbook before closing.

**Comment by char0n** [comment]
Ref: https://github.com/char0n/ramda-adjunct/issues/181

**Comment by char0n** [comment]
Documented on [ramda cookbook](https://github.com/ramda/ramda/wiki/Cookbook#omitindexes). Closing.
