### ISSUE TITLE
Add search in documentation

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#24]
- [ ] search
- [x] category annotations
- [ ] filtering by category annotations

**Comment by char0n** [comment]
@rockymadden, @BjornMelgaard pls find a couple of minutes to check the new docs here: https://char0n.github.io/ramda-adjunct/2.0.0/

Please let me know about if you find something incorrect or wrong. We will go for 2.0.0 tomorrow with this new docs and full support for tree shaking.

**Comment by rockymadden** [comment]
@char0n, a couple items:

- The search bar itself is not visible in mobile safari (though it is present).
- Searching seems to look for both type and name. In the case of looking for type `function`, functions ending with `Function` are shown.

**Comment by char0n** [comment]
@rockymadden thanks for review.

> The search bar itself is not visible in mobile safari (though it is present).

The entire mobile version of docs is fucked. I have created issue for it: https://github.com/char0n/ramda-adjunct/issues/201. It will need some time investments.

> Searching seems to look at both category and name. In the case of looking for the category function, functions with names including Function are shown.

Yes I know about that. It is by design to keep searching/filtering simple/consistent and aligned with ramda docs. When search happens we search through function names and their category. Do you have any suggestions how to make it better and still only use one simple search input ?

**Comment by BjornMelgaard** [comment]
@char0n 

1. lost `}` in the end of `mergeProp` example  (`{ outer: { foo: 3, bar: 4 }` instead of `{ outer: { foo: 3, bar: 4 } };`)
2. in examples, background color not preserved on overflow 
![2017-11-08-11 22 57-screenshot](https://user-images.githubusercontent.com/7573215/32541051-30e1b43c-c477-11e7-8e77-babe4622bfc2.png)
3. lost `:` in the end of `spreadPath` example (`{ a: 1, c: 3, d: 4, b1 {} };` instead of `{ a: 1, c: 3, d: 4, b1: {} };`)

Too bad we didn't made cross-references between `spread*` and `flatten*`, something like 
```
flattenPath:
...description
It's like spreadPath, but preserves object under property path
```
would be very helpful

**Comment by char0n** [comment]
@BjornMelgaard pls create a PR for the things you describe about flattenPath, mergeProp. I'll deal with the documentation layout fixes.
