### ISSUE TITLE
mapIndexed

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#282]
```js
// indexedMap :: Functor f => ((a, c, [a]) -> b) -> f a -> f b
export const indexedMap = addIndex(map);

**Comment by guillaumearm** [comment]
It's the `imap` function in #38

**Comment by Undistraction** [comment]
It's a very simple one, but I use all the time so I think it's definitely worth adding.

**Comment by Undistraction** [comment]
Probably worth adding an `indexedReduce` too: 
```
export const indexedReduce = addIndex(reduce);
```

**Comment by guillaumearm** [comment]
You right.

+ I'm ok with `iMap` and `iReduce` functions name.

**Comment by char0n** [comment]
I'd stick with `indexedMap` because it really says what it does. I can imagine having `iMap` alias. But even maybe adding alias doesn't make sense because in es6 imports we can already do aliases
```js
import { indexedMap as iMap } from 'ramda-adjuct';
```
or
```js
import { indexedMap as imap } from 'ramda-adjuct';
```

**Comment by char0n** [comment]
And to be consistent with ramda I'd rename to `mapIndexed`

**Comment by Undistraction** [comment]
I think the problem with using Indexed here is that Ramda already uses `indexed` to mean something else. `mapObjIndexed` passes the key and object itself in addition to the value (value, key, obj), but no index. In this respect having a mapIndexed is imho confusing. I think that given that `addIndex` adds a numeric index and can be used with `mapObjIndexed` to further add a numeric index (value, key, obj, index), the problem is actually with Ramda's naming of `mapObjIndexed` which should have been called something like `mapObjKeyed`. So we want to have a `mapObjIndexed` which doesn't actually add an index alongside `mapIndexed` which does? I could see utilty in creating a separate mapObjIndex with a numeric index, but what would that be named?

```
const mapObjIndexedWithIndex = addIndex(mapObjIndexed);

const a = {
 a: 'alpha',
  b: 'bravo',
  c: 'charlie'
}

const implementation = mapObjIndexedWithIndex(
  (value, key, o, index) => 
      join(': ', [index, key, value])
)

implementation(a) // {"a": "0:a:alpha", "b": "1:b:bravo", "c": "2:c:charlie"}
```

[REPL](http://ramdajs.com/repl/?v=0.25.0#?const%20mapObjIndexedWithIndex%20%3D%20addIndex%28mapObjIndexed%29%3B%0A%0Aconst%20a%20%3D%20%7B%0A%20a%3A%20%27alpha%27%2C%0A%20%20b%3A%20%27bravo%27%2C%0A%20%20c%3A%20%27charlie%27%0A%7D%0A%0Aconst%20implementation%20%3D%20mapObjIndexedWithIndex%28%0A%20%20%28value%2C%20key%2C%20o%2C%20index%29%20%3D%3E%20%0A%20%20%20%20%20%20join%28%27%3A%20%27%2C%20%5Bindex%2C%20key%2C%20value%5D%29%0A%29%0A%0Aimplementation%28a%29%20%2F%2F%20%7B%22a%22%3A%20%220%3Aa%3Aalpha%22%2C%20%22b%22%3A%20%221%3Ab%3Abravo%22%2C%20%22c%22%3A%20%222%3Ac%3Acharlie%22%7D)

**Comment by char0n** [comment]
I guess ramda made a unfortunate decision when naming `mapObjIndexed`. I'd name it `mapObjKeyed` too. This error/inconsistency should not deter us from naming our functions property. In https://github.com/char0n/ramda-adjunct/issues/66 we want to define predicate called `isIndexed`. In javascript indexed are Arrays and Strings (Set, Map don't apply, and objects converts their keys to strings). So in this context and in my mind naming the function `mapIndexed` is be most correct thing we can do.

**Comment by guillaumearm** [comment]
I have no problem with `mapIndexed` name

**Comment by guillaumearm** [comment]
I can take this one + #281 ?

**Comment by char0n** [comment]
Cool go for it.

**Comment by char0n** [comment]
@guillaumearm is taking care of this for 2.5.0
