### ISSUE TITLE
hasView / viewHas

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#303]
I've only recently started using lenses, but it appears there is no easy way of checking to see if a prop exists. `view` returns the value of a property focused on by a lens and `set` sets that property. I know there are other options for transforming the property, but not an equivalent of `has`:

```javascript
const o ={
  a: 1
}

const lensPropA = lensProp('a');
const lensPropB = lensProp('b');

const hasView = lens => compose(isNotUndefined, view(lens));
const hasViewA = hasView(lensPropA);
const hasViewB = hasView(lensPropB);

hasViewA(o) // true
hasViewB(o) // false
```
[REPL](http://ramdajs.com/repl/#?const%20o%20%3D%7B%0A%20%20a%3A%201%0A%7D%0A%0Aconst%20isNotUndefined%20%3D%20complement%28equals%29%28undefined%29%0Aconst%20lensPropA%20%3D%20lensProp%28%27a%27%29%3B%0Aconst%20lensPropB%20%3D%20lensProp%28%27b%27%29%3B%0A%0Aconst%20hasView%20%3D%20lens%20%3D%3E%20compose%28isNotUndefined%2C%20view%28lens%29%29%3B%0Aconst%20hasViewA%20%3D%20hasView%28lensPropA%29%3B%0Aconst%20hasViewB%20%3D%20hasView%28lensPropB%29%3B%0A%0AhasViewA%28o%29%20%2F%2F%20true%0AhasViewB%28o%29%20%2F%2F%20false%0A)

Worth adding or is this covered already?

**Comment by char0n** [comment]
Isn't this what you are looking for ? https://char0n.github.io/ramda-adjunct/2.4.0/RA.html#.lensSatisfies

**Comment by Undistraction** [comment]
Not really, though that could be used with `isNotUndefined` for the same result:
```
const o = { a:1 };
RA.lensSatisfies(RA.isNotUndefined, R.lensProp('a'), o); // true
RA.lensSatisfies(RA.isNotUndefined, R.lensProp('b'), o); // false
```
What I am suggesting is a function that returns `true` if the property exists at the location focussed by the lens and `false` if not:
```
RA.viewHas(R.lensProp('a'), o) // true
RA.viewHas(R.lensProp('b'), o) // false
```

**Comment by char0n** [comment]
I don't think that is possible. As I studied lenses and their implementation in ramda, primitive lenses are configured with getters and setters. Imagining `viewHas` would exist, it would still not solve the problem by telling you if the property exist or no, because in javascript property may exist but may be set to undefined. Which is big difference in behavior. I saw you went through [this article](https://www.linkedin.com/pulse/functional-lenses-javascript-vladim%C3%ADr-gorej/), so you are already familiar with the subject.

The problem is solvable by lens it self at creation phase; observe:

**Read/Write lens**
```js
const lens = R.lens(R.has('property'), R.assoc('property'));

R.view(lens, { property: 3 }); //=> true
R.view(lens, { }); //=> false
```

**Read only lens**
```js
const lens = R.lens(R.has('property'), R.nthArg(1));

R.view(lens, { property: 3 }); //=> true
R.view(lens, { }); //=> false
```

So I can imagine having `lensHas` and `lensHasPath` that should adhere to read only implementation example and one can use `view` function to look through the lens.

**Comment by Undistraction** [comment]
Yes. That makes sense. The view is just executing the lens' getter so even if it wanted cannot to, it  know which prop is being focused on to check if it exists. Do you see utility in `lensHas` and `lensHasPath`? 

Those articles were really good by the way. You write well.

**Comment by char0n** [comment]
> Yes. That makes sense. The view is just executing the lens' getter so even if it wanted cannot to, it know which prop is being focused on to check if it exists. Do you see utility in lensHas and lensHasPath?

I think I do see utility in them. I can imagine a lot of people may be struggling with this (on academical level). But I doubt the real applications. People create lenses to focus on particular piece of data. If you cannot reuse the same lens to check if the data is really there or not, and have to create new one with (`lensHas`, `lensHasPath`) for this usecase ... well it just doesn't make sense to me. IMHO lens should focus on the data and we have `has` and `hasPath` for inspecting if the path really exists. Due to the javascript implementation it is not possible to distinguish if the path contains the `undefined` or the path doesn't exist at all. From the data point of view, it's the same thing.

> Those articles were really good by the way. You write well.
Thank you, glad you liked it.
