### ISSUE TITLE
Ensure running 'prettier'

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#379]
Because I just run prettier on master and there are some changes, I think we need to discuss on that, there are several solutions.

Ideas : 
- Separate style fixes in a a specific rule (`npm run lint:fix`)
- Run prettier on a precommit hook (staged files only, using husky and lint-staged #314)

@GingerPlusPlus : Can you confirm me your prettier does nothing on master ?

**Comment by Undistraction** [comment]
By far the easiest solution is to have prettier run on save for your editor. I use VSCode and the integration is seamless - I get all the ESLint errors displayed inline and every time I save Prettier formats the code. This is particularly great because I no longer need to think about formatting my code at all. I can type whatever I need straight in, using snippets as needed, and just save to get everything formatted which is a huge timesaver (and ensures I save regularly). 

However this doesn't solve consistency issues with PRs etc. For my own projects I have Husky set up to run effectively `lint & eslint` before every commit and run `lint & eslint & test & build` before every push. 

Imho asking people to remember to do something - especially someone who might be committing to the project for the first time - is always going to cause issues. Linting / formatting of both code and commit messages should be automatic. This is the only way we can ensure consistency.

**Comment by char0n** [comment]
IMHO I think the consistency needs to be enforced on the CI level. I suggest the following:

1.) extract prettier as independent `script`  in `package.json`.
2.) create a new script in ./scripts/prettier-changes-detection.js that will detect if there are unstaged changes on CI (using git internaly; return exit codes 0 or 1)

Workflow:

When somebody pushes commit or create PR, we will run `npm run prettier` and then `node ./scripts/prettier-changes-detection.js`. If script detects something changed the build will fail.


Documentation:

We will also mention prettier in CONTRIBUTING.md guilde line as part of the developer workflow.

What do you think ?

**Comment by Undistraction** [comment]
I absolutely think it should be enforced at CI level, but if we can catch linting errors or formatting errors before then - before they end up in PRs then I'm up for that as well - it is less noise, less frustration and less wasted time for committers having to address small niggles. 

@char0n What is your argument against using Githooks for this - I can see there is a potential argument that it is unexpected, but I think this can be dealt with in the docs. There is also the fact it can be quite opaque if managing Git with an IDE - for example I use Tower for Git as I find great benefit from a good graphical representation of commit history etc (I think very visually) and it is non-obvious what is happening when the hooked scripts are being run.

**Comment by guillaumearm** [comment]
@char0n : I think it's a good solution, and no breaking changes in development workflow is a plus (lint:fix continue to run prettier --write).

But I like the other solution too because `npm run lint` should be immutable for the codebase (IMHO).

--------------------------

@Undistraction  :

>  if we can catch linting errors or formatting errors before then - before they end up in PRs then I'm up for that as well - it is less noise, less frustration and less wasted time for committers having to address small niggles.

totally agreed with you on this, IMHO, this is complementary to the rest.

For the hook, Instead running all the `lint` command, we can use `lint-staged` for fast commiting.

**Comment by Undistraction** [comment]
> For the hook, Instead running all the lint command, we can use lint-staged for fast commiting.

I find a separate hook for committing and pushing is good - keep the commit hook lightweight (and fast) - just `lint and format` then add `test` and `build` for push.

**Comment by guillaumearm** [comment]
In fact, I think we should re-open #314 to discuss about it.

For hooks, I'm ok with adding a strong prepush hook, but personally, I hate waiting when I commit something, this is why I removed lint-staged from my project.

Add a pre-commit hooks to pass prettier is a good thing, but this will embarrass people who use prettier on save.

A solution is to add this hook anyway, and folks who don't want to use it can `rm .git/hooks/precommit`

**Comment by guillaumearm** [comment]
I just open #381, let's just decide here which solutions is preferable (for CI check)

**Comment by guillaumearm** [comment]
I added this issue to the [2.6.0 milestone](https://github.com/char0n/ramda-adjunct/milestone/9) because it's directly related to #336.

**Comment by guillaumearm** [comment]
closed via #388
