### ISSUE TITLE
RA.alwaysTrue, RA.alwaysFalse

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#398]
I really really hate R.T and R.F. They are so opaque. How about we add aliases for them:

```
RA.alwaysTrue
RA.alwaysFalse
```

Thoughts?

**Comment by char0n** [comment]
Yes I agree they are opaque. But as long as we already have `stub*` functions in RA I'd stick with that. 
```js
RA.stubTrue
RA.stubFalse
```
The question is, do we want to do something like that ? Aliasing ramda function may lead to some really dark places. Aliasing generally does.

IMHO I think that we don't need to do that anymore because of object destructuring and ES6 import aliasing, which makes this possible on library consumer level without any additional hassle.

```js
const { T: stubTrue } = require('ramda');
import { T as stubTrue } from 'ramda';
```

**Comment by Undistraction** [comment]
Yes. I completely forgot we already had `stubTrue`/`stubFalse`.

**Comment by char0n** [comment]
We don't. I was just trying to describe that we can alias R functions
directly during imports and adhere to stubuing naming.

**Comment by Undistraction** [comment]
Well in that case, I think adding `RA.stubTrue` and `RA.stubFalse` would absolutely make sense for consistency, but in practical terms I guess aliasing Ramda functions is probably not the way to go.

**Comment by char0n** [comment]
Agree. Destructuring and import aliasing seem like an appropriate solution.
