### ISSUE TITLE
isFloat fails when .00

### ISSUE THREAD

**Issue by vorticalbox** [char0n/ramda-adjunct#741]
When checking for floats if it is .00 it returns false

```javascript
const R = require('ramda');
const RA = require('ramda-adjunct');

console.log(RA.isFloat(123.00)) //false
```

**Comment by char0n** [comment]
You are right that it behaves like this. The problem here that his is supposed to be correct behavior. In JavaScript `1.00` is always coerced to integer. We're using `Number.isInteger` under the hood for `RA.isInteger` to detect if the value is integer and this predicate really returns true for the following cases:
```js
Number.isInteger(0.00); // => true
Number.isInteger(1.00); // => true
```

If you check any other library like lodash, underscore or even native `Number.isInteger` the behavior is consistent. If you're concerned with this behavior checkout for example [decimal.js](https://github.com/MikeMcl/decimal.js/) which tries to overcame this problem by representing numbers as strings to avoid that. 

You could also use [validator](https://www.npmjs.com/package/validator) library to check is the value is Float or Integer, but the library consumes all values only in strings. The reason is exactly the same as before - implicit coercing. Only in strings additional `*.00` zeros will be preserved.

**Comment by vorticalbox** [comment]
Thanks for the quick reply, I am currently using validator as I need the number to be in xx.xx format.

**Comment by char0n** [comment]
Np
