### ISSUE TITLE
Alias then conflicts with ramda then

### ISSUE THREAD

**Issue by razor-x** [char0n/ramda-adjunct#795]
I maintain a package that depends on ramda and ramda-adjunct having non-conflicting exports (we basically re-export everything under a single namespace). I realize this is not necessarily guaranteed by this project, however it (A) has not been an issue before and (B) seems like a reasonable assumption that there would not exist functions in each project under the same name.

Anyway, I need to plan for the future, so I have a few questions that will help me

1. Will `then` be remove from the exports of `RA` in a near-future version?
2. Will RA make any future commitment to non-conflicting function names?
3. Why was the `then` alias added? It's only documented in the CHANGELOG and it was not a function in RA before the version the alias was added.
4. Not a question, but our team :heart:  RA.

**Comment by char0n** [comment]
Hi @razor-x,

> seems like a reasonable assumption that there would not exist functions in each project under the same name

Yes, the assumption is right. It would not make sense to have two functions in both projects with the same name. But you have to keep in mind that our support for ramda spans multiple versions: ramda >= 0.19.0 <= 0.26.1. That's why I've chosen  the aliasing strategy for  `thenP`. What I was trying to do was to align the RA naming to what R chosen to call this function `then`. So my intention was to alias our `RA.thenP` so that people get used to using `RA.then` instead of `RA.thenP` and then eventually migrate to `R.then` and remove it from our codebase if we just have to support ramda >= 0.26.0

> 1.) Will then be remove from the exports of RA in a near-future version?

Well my original plan was to remove it as it has already become part of ramda. But when this happens I don't know. As we're trying to keep compatibility with ramda >= 0.19.0 <= 0.26.1, it still make sense to retain `RA.thenP` until we would be forced to drop the compatibility for older ramda versions and only support ramda >= 0.26.0. 

> 2.) Will RA make any future commitment to non-conflicting function names?

It's hard to say. As we support multiple versions of ramda that may or may not have this function, it just make sense to have a conflicting function name for limited period of time in the codebase. As mission of RA is also push RA functions in R core, this may happen more frequently.

> 3.) Why was the then alias added? It's only documented in the CHANGELOG and it was not a function in RA before the version the alias was added.

`RA.thenP` was function in RA for a long time. Refer to this [history](https://github.com/char0n/ramda-adjunct/commits/master/src/thenP.js) log.

> 4.) Not a question, but our team heart RA.

Thank you. I'm glad RA found it's place in modern FP ;] Hopefully I answered all your questions. Sorry if my strategy for conflicting names created an issue for you. Can you solve it ? Can I do something to help you ?

**Comment by razor-x** [comment]
Thanks. I understand that `RA.thenP` was a function, but the `RA.then` alias is new. I see how adding `RA.then` can help transition people who cannot upgrade to the latest Ramda, although I'm not sure I would have taken the same approach. I had also not considered the issue of supporting a range of previous ramda versions and the transition of functions into core.

I think my only option in this case is to move from 

```
export * from 'ramda'
export * from 'ramda-adjunct'
```

to 

```
export * from 'ramda'
export {
  isNil,
  isNotEmpty,
  ...,
} from 'ramda-adjunct'
```

Obviously not as convenient for me, but still possible (wanted to check in before I pulled the trigger, thanks for getting back to me). Incidentally merging the namespaces of R, RA, and some of our own extra fns as a package has been a huge productivity boost (no need to remember what pkg to import from, keeps versions consistent, etc.)

**Comment by char0n** [comment]
> although I'm not sure I would have taken the same approach
I'm open to suggestions here. What approach would you suggest ? 

I think you can still acheive what you want by using [webpack aliases](https://webpack.js.org/configuration/resolve/#resolve-alias). Create a local module, reexporting only non conflicting stuff and make webpack read from it when hitting 'ramda-adjunct' import.

There is also a medium publication regarding ramda-adjunct that explains all the changes we do to the library. Maybe worth following for you: https://medium.com/ramda-adjunct

**Comment by razor-x** [comment]
I would have not added the alias and just let users transition directly from `RA.thenP` to `R.then` when they were able to update ramda. However I have a particular bias here so I can't say if that's really a better idea. Either way removing `RA.then` would be a breaking change at this point so I don't recommend backtracking that choice. As longs the creation of aliases are generally consistent I think it's a reasonable approach now that's it's explained.

I can't really use aliases here as we don't use webpack in all projects and the goal is to merge the namespaces in a single package. Anyway I've simply re-exported RA fns by name. As long as the R and RA changelogs remain descriptive about what is added / removed I can keep things updated easily enough.

Thanks the the link, definitely something I'll be watching. I'll need to watch out for some of those breaking changes :thinking:
