### ISSUE TITLE
Rename polyfills to ponyfills

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#903]
**Is your feature request related to a problem? Please describe.**

All through out the codebase, we call our ponyfill - polyfills. This is incorrect. We're not polyfilling anything, we just provide ponyfills that can be utilized. 

**Describe the solution you'd like**

All files, directories, variable names, test descriptions needs to changed from `polyfill` to `ponyfill`. When we finish no reference to word `polyfill` can be found in the project.

**Describe alternatives you've considered**

---

**Additional context**

https://ponyfoo.com/articles/polyfills-or-ponyfills

**Comment by tomokos2** [comment]
Hi, may I work on this?

**Comment by tomokos2** [comment]
There are references to Polyfill inside the babel files as well, but should I rename those as well?

**Comment by char0n** [comment]
@tomokos2 sure go ahead and git it a try!

> There are references to Polyfill inside the babel files as well, but should I rename those as well?

Not sure I understand what you mean by this. Can you be more specific?

**Comment by tomokos2** [comment]
Hi, I made a PR regarding this issue, but I am not passing a test in code climate for the PR. I did not change any code for that specific file, so I am unsure of what to do in order to pass the test. I have attached a picture of the failed test as reference.
[
![Screenshot (516)](https://user-images.githubusercontent.com/54867150/84191457-22759380-aa5e-11ea-8ae0-e39ef81ce3c3.png)
](url)

**Comment by char0n** [comment]
Don't worry about that one. I need to approve it explicitly in codeclime. It has been approved in past, but because of the renaming I have to re-approve it again. This code is directly adopted from [MDN site](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#Polyfill).
